-- Business question:
-- What percentage of total revenue is generated by the top 10 sellers?

-- Business Context:
-- Identify how concentrated seller revenue is by measuring the contribution
-- of the highest-revenue sellers to overall seller revenue.

-- SQL Concepts:
-- CTEs, JOINs, aggregate functions, window functions (RANK),
-- subqueries, filtering, and percentage calculations.

WITH seller_revenue AS (
    SELECT
        seller_id,
        SUM(price)::numeric AS revenue
    FROM order_items
    GROUP BY seller_id
),

ranked_sellers AS (
    SELECT
        seller_id,
        revenue,
        RANK() OVER (
            ORDER BY revenue DESC
        ) AS seller_rank
    FROM seller_revenue
)

SELECT
    COUNT(*) AS top_10_sellers,

    ROUND(
        SUM(revenue),
        2
    ) AS top_10_revenue,

    ROUND(
        100 * SUM(revenue)
        / (SELECT SUM(revenue) FROM seller_revenue),
        2
    ) AS revenue_percentage

FROM ranked_sellers
WHERE seller_rank <= 10;

-- Key Finding:
-- The top 10 sellers generated 1,787,241.74 in revenue,
-- representing 13.15% of total seller revenue.