-- Business question: How many orders does each order status have?
-- SQL concepts: GROUP BY, COUNT
 
SELECT
    order_status,
    COUNT(order_id) AS order_count
FROM orders
GROUP BY order_status;
 
 
-- Business question: What is the total revenue generated by each payment type?
-- SQL concepts: GROUP BY, SUM
 
SELECT
    payment_type,
    SUM(payment_value) AS total_revenue
FROM order_payments
GROUP BY payment_type;
 
 
-- Business question: Which product categories have more than 100 products listed?
-- SQL concepts: GROUP BY, COUNT, HAVING
 
SELECT
    product_category_name,
    COUNT(product_id) AS product_count
FROM products
GROUP BY product_category_name
HAVING COUNT(product_id) > 100;
 
 
-- Business question: What is the average review score for each score count, to see how ratings cluster?
-- SQL concepts: GROUP BY, AVG, COUNT combined
 
SELECT
    review_score,
    COUNT(review_id) AS number_of_reviews
FROM order_reviews
GROUP BY review_score
ORDER BY review_score;
 
 
-- Business question: Which sellers have processed more than 50 order items?
-- SQL concepts: GROUP BY, COUNT, HAVING on a different table
 
SELECT
    seller_id,
    COUNT(order_item_id) AS items_sold
FROM order_items
GROUP BY seller_id
HAVING COUNT(order_item_id) > 50;
 
 
-- Business question: What are the top 5 customer states by total number of orders?
-- SQL concepts: GROUP BY, COUNT, ORDER BY, LIMIT combined
 
SELECT
    customer_state,
    COUNT(order_id) AS order_count
FROM customers
GROUP BY customer_state
ORDER BY order_count DESC
LIMIT 5;